[project]
name = "ensurevault"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.1",
    "mysql-connector-python>=9.5.0",
    "uvicorn>=0.40.0",
]
